apiVersion: v1
kind: ConfigMap
metadata:
  name: cdm-minio-service-config
  namespace: cdm-jupyterhub
data:
  MINIO_ENDPOINT: "http://minio:9002"
  MINIO_ROOT_USER: "minio"
  MINIO_ROOT_PASSWORD: "minio123"
  KBASE_AUTH_URL: "https://ci.kbase.us/services/auth/"
  KBASE_ADMIN_ROLES: "CDM_JUPYTERHUB_ADMIN"
  KBASE_REQUIRED_ROLES: "BERDL_USER"